stages:
  - validating
  - differentiating
  - synchronizing
  - backup
  - uploading

variables:
  LABEL_ID: 1
  ASSETS_GLOB: assets/*.yml
  ASSETS_SCHEMA: schemas/demo.job_template.schema.yml

  BACKUP_PATH: &backup_path backup    # path to backup
  ARTIFACTS_JOB: &backup_job backup   # name of backup job in gitlab-ci


.common: &common
  image: europ/atacac:latest
  tags:
    - upshift


validation:
  <<: *common
  stage: validating
  script:
    - yamllint .
    - atacac validate

differentiation:
  <<: *common
  stage: differentiating
  script:
    - atacac differentiate
  allow_failure: true

synchronization:
  <<: *common
  stage: synchronizing
  script:
    - atacac synchronize

*backup_job:
  <<: *common
  stage: backup
  only:
    - master
  script:
    - atacac backup
  artifacts:
    paths:
      - *backup_path

upload:
  <<: *common
  stage: uploading
  only:
    - master
  script:
    - atacac upload
