---
dist: bionic # Ubuntu 18.04
language: minimal

matrix:
  include:
    - name: Linter-Dockerfile (hadolint)
      language: minimal
      services:
        - docker
      before_install:
        - docker pull hadolint/hadolint
      script:
        - >
          docker run --rm -i
          -v ${PWD}/.conf/hadolint.yaml:/conf/hadolint.yaml:Z
          -e XDG_CONFIG_HOME=/conf hadolint/hadolint
          < Dockerfile

    - name: Linter-Markdown (markdownlint)
      language: ruby
      rvm: 2.7.1
      before_install:
        - gem install mdl
      script:
        - mdl --style ./.conf/markdownlint.rb .

    - name: Linter-Python (flake8,mypy,pylint)
      language: python
      python: 3.8
      before_install:
        - pip install tox
      script:
        - tox -e flake8,mypy,pylint

    - name: Linter-YAML (yamllint)
      language: python
      python: 3.8
      before_install:
        - pip install tox
      script:
        - tox -e yamllint
